CREATE TABLE Customers(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    FirstName VARCHAR(30) NOT NULl,
    LastName VARCHAR(40) NOT NULL,
    Email VARCHAR(128) NOT NULL UNIQUE,
    Phone VARCHAR(15),
    Address VARCHAR(20),
    PostalCode CHAR(5),
    City VARCHAR(15)
);

ALTER TABLE Customers
    ADD COLUMN Age INTEGER;

ALTER TABLE Customers
    ADD COLUMN Gender CHAR(1);

-- DROP TABLE Customers;

CREATE TABLE Orders(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    OrderNumber VARCHAR(12) NOT NULL
);

ALTER TABLE Orders ADD CONSTRAINT OrderNumber varchar(12) UNIQUE;

-- DROP TABLE Orders;

-- CREATE TABLE Products...
CREATE TABLE Products(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ItemNumber VARCHAR(15) NOT NULL UNIQUE,
    Name VARCHAR(20) NOT NULL,
    Price FLOAT NOT NULL
);
